alias nconf="cd ~/.config/nvim"
alias proj="cd ~/Projects"
alias aws="cd ~/.config/awesome"
alias fide="cd ~/.config/fish"
alias lef="cd ~/.config/lf"

alias lg="lazygit"
alias lf="lfcd"
alias sx="startx"
alias umnt="fusermount -u"
alias phonemnt="aft-mtp-mount"
alias qq="devour neovide --no-fork"
# alias neovide="neovide --no-vsync"
# devour neovide --no-fork

alias sudo="doas"
alias pac="doas pacman"
alias yay="yay --noconfirm"
alias aurupt="yay -Syyu"
alias upt="doas pacman -Syu"
alias std="shutdown now"
alias ssp="systemctl suspend"
alias knv="killall"
