[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[shell]
args = ["--private"]
program = "/run/current-system/sw/bin/fish"

[window]
opacity = 1.0
